package autoclicker;

// GitHub: Phoeyuh

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.event.InputEvent;
import javax.swing.JOptionPane;

public class MainGUI extends javax.swing.JFrame {

    private int Clicks = 0;
    private boolean autoclickerRunning = false;
    private Robot robot;
    
    public MainGUI() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon.png")));
        initComponents();
        try {
            robot = new Robot();
        } catch (AWTException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround2 = new javax.swing.JPanel();
        MainFrameButton1 = new javax.swing.JButton();
        SettingsFrameButton = new javax.swing.JButton();
        TabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        StopButton = new javax.swing.JButton();
        StartButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ClicksLabel = new javax.swing.JLabel();
        DelayField = new javax.swing.JTextField();
        StartingDelayField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AutoClicker");
        setMinimumSize(new java.awt.Dimension(280, 147));
        setPreferredSize(new java.awt.Dimension(280, 147));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackGround2.setBackground(new java.awt.Color(30, 33, 36));

        MainFrameButton1.setBackground(new java.awt.Color(66, 69, 73));
        MainFrameButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MainFrameButton1.setForeground(new java.awt.Color(255, 255, 255));
        MainFrameButton1.setText("MAIN");
        MainFrameButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MainFrameButton1.setBorderPainted(false);
        MainFrameButton1.setFocusPainted(false);
        MainFrameButton1.setFocusable(false);
        MainFrameButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainFrameButton1ActionPerformed(evt);
            }
        });

        SettingsFrameButton.setBackground(new java.awt.Color(66, 69, 73));
        SettingsFrameButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SettingsFrameButton.setForeground(new java.awt.Color(255, 255, 255));
        SettingsFrameButton.setText("SETTINGS");
        SettingsFrameButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SettingsFrameButton.setBorderPainted(false);
        SettingsFrameButton.setFocusPainted(false);
        SettingsFrameButton.setFocusable(false);
        SettingsFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsFrameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackGround2Layout = new javax.swing.GroupLayout(BackGround2);
        BackGround2.setLayout(BackGround2Layout);
        BackGround2Layout.setHorizontalGroup(
            BackGround2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGround2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackGround2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainFrameButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(SettingsFrameButton, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        BackGround2Layout.setVerticalGroup(
            BackGround2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGround2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(MainFrameButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettingsFrameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(BackGround2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        jPanel1.setBackground(new java.awt.Color(66, 69, 73));

        StopButton.setBackground(new java.awt.Color(114, 137, 218));
        StopButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StopButton.setForeground(new java.awt.Color(255, 255, 255));
        StopButton.setText("STOP");
        StopButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        StopButton.setBorderPainted(false);
        StopButton.setFocusPainted(false);
        StopButton.setFocusable(false);
        StopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopButtonActionPerformed(evt);
            }
        });

        StartButton.setBackground(new java.awt.Color(114, 137, 218));
        StartButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StartButton.setForeground(new java.awt.Color(255, 255, 255));
        StartButton.setText("START");
        StartButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        StartButton.setBorderPainted(false);
        StartButton.setFocusPainted(false);
        StartButton.setFocusable(false);
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(StopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        TabbedPane1.addTab("tab1", jPanel1);

        jPanel2.setBackground(new java.awt.Color(66, 69, 73));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(253, 253, 253));
        jLabel4.setText("Delay");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(253, 253, 253));
        jLabel6.setText("ms");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(253, 253, 253));
        jLabel7.setText("Clicks:");

        ClicksLabel.setBackground(new java.awt.Color(255, 255, 255));
        ClicksLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ClicksLabel.setForeground(new java.awt.Color(114, 137, 218));
        ClicksLabel.setText("0");

        DelayField.setBackground(new java.awt.Color(253, 253, 253));

        StartingDelayField.setBackground(new java.awt.Color(253, 253, 253));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(253, 253, 253));
        jLabel8.setText("ms");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(253, 253, 253));
        jLabel9.setText("Starting Delay");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DelayField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClicksLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StartingDelayField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(StartingDelayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(DelayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ClicksLabel))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        TabbedPane1.addTab("tab2", jPanel2);

        getContentPane().add(TabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, 180, 160));

        setSize(new java.awt.Dimension(298, 125));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SettingsFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsFrameButtonActionPerformed
        TabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_SettingsFrameButtonActionPerformed

    private void MainFrameButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainFrameButton1ActionPerformed
        TabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_MainFrameButton1ActionPerformed

    private void StopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
        autoclickerRunning = false;
    }//GEN-LAST:event_StopButtonActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
    String startingDelayText = StartingDelayField.getText();
    String clickDelayText = DelayField.getText();

    if (startingDelayText.isEmpty() || clickDelayText.isEmpty()) {
        // Error messgae for missing values message
        JOptionPane.showMessageDialog(this, "Please enter valid values for delay fields.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit without starting the autoclicker
    }

    try {
        int startingDelay = Integer.parseInt(startingDelayText);
        int clickDelay = Integer.parseInt(clickDelayText);

        if (startingDelay < 0 || clickDelay < 0) {
            // Error message for negative values
            JOptionPane.showMessageDialog(this, "Please enter non-negative values for delay fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit without starting the autoclicker
        }

        if (!autoclickerRunning) {
            autoclickerRunning = true;

            new Thread(() -> {
                try {
                    robot.delay(startingDelay);

                    while (autoclickerRunning) {
                        robot.mousePress(InputEvent.BUTTON1_MASK);
                        robot.mouseRelease(InputEvent.BUTTON1_MASK);

                        robot.delay(clickDelay);
                        ClicksLabel.setText("" + Clicks++);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }).start();
        }
    } catch (NumberFormatException e) {
        // Error message for non-numeric input
        JOptionPane.showMessageDialog(this, "Please enter valid numeric values for delay fields.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_StartButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround2;
    private javax.swing.JLabel ClicksLabel;
    private javax.swing.JTextField DelayField;
    private javax.swing.JButton MainFrameButton1;
    private javax.swing.JButton SettingsFrameButton;
    private javax.swing.JButton StartButton;
    private javax.swing.JTextField StartingDelayField;
    private javax.swing.JButton StopButton;
    private javax.swing.JTabbedPane TabbedPane1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
